name: Lint, Test, Build, and Deploy

on:
  push:
    branches:
      - main  # Выполнять действие при пуше в ветку main
  pull_request:  # Также выполнять при открытии pull request
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Run Jest tests
        run: npm run test -- --ci

      - name: Build project
        run: npm run build
